### ISSUE TITLE
7.3. Todo List API 

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-03-react-hello#28]
# TODO List API

https://playground.4geeks.com/todo/docs

- [ ] Create your todolist with [POST] /todos/user/<username>. (you can pick any username)
- [ ] Update your todolist with [PUT] /todos/user/<username>, you have to pass the whole todolist every time.
- [ ] Delete your todolist (if needed) [DELETE] /todos/user/<username>.

**Comment by hchocobar** [comment]
- [ ] Create updateTodos para que soporte la modificiación de una tarea y la elimnación de una tarea
